config:
  no-trailing-spaces: false
  no-multiple-blanks: false
  MD033: false
  MD013: false
  MD041: false
  MD003: false
fix: true
gitignore: true
frontMatter: "/^---[\\s\\S]*?---$/m"
globs:
  - "**/*.md"
ignores:
  - "slides/theme/example.md"
  - "pages/curriculum/curriculum.md"
  - "slides/**/*.md"
noBanner: false
noInlineConfig: true
noProgress: false
outputFormatters:
  - - markdownlint-cli2-formatter-default
showFound: true
